//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MiniCPP.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MiniCPPParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMiniCPPListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MiniCPPParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MiniCPPParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.includeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncludeStmt([NotNull] MiniCPPParser.IncludeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.includeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncludeStmt([NotNull] MiniCPPParser.IncludeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] MiniCPPParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] MiniCPPParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDecl([NotNull] MiniCPPParser.FuncDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDecl([NotNull] MiniCPPParser.FuncDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] MiniCPPParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] MiniCPPParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] MiniCPPParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] MiniCPPParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDecl([NotNull] MiniCPPParser.StructDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDecl([NotNull] MiniCPPParser.StructDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MiniCPPParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MiniCPPParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] MiniCPPParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] MiniCPPParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDecl([NotNull] MiniCPPParser.ConstDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDecl([NotNull] MiniCPPParser.ConstDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDecl([NotNull] MiniCPPParser.ConstructorDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDecl([NotNull] MiniCPPParser.ConstructorDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.destructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDestructorDecl([NotNull] MiniCPPParser.DestructorDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.destructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDestructorDecl([NotNull] MiniCPPParser.DestructorDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] MiniCPPParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] MiniCPPParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.controlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStruct([NotNull] MiniCPPParser.ControlStructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.controlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStruct([NotNull] MiniCPPParser.ControlStructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] MiniCPPParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] MiniCPPParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MiniCPPParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MiniCPPParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MiniCPPParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] MiniCPPParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MiniCPPParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] MiniCPPParser.ExprContext context);
}
