//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/elena/OneDrive/Documente/Facultate-INFORMATICA/An_2/sem1/LFC/ANTLR-poj3/ANTLR-poj2/ANTLR-poj2/MiniCPP.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MiniCPPParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMiniCPPVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MiniCPPParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.includeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncludeStmt([NotNull] MiniCPPParser.IncludeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] MiniCPPParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDecl([NotNull] MiniCPPParser.FuncDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] MiniCPPParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] MiniCPPParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.structDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDecl([NotNull] MiniCPPParser.StructDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MiniCPPParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] MiniCPPParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.constDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstDecl([NotNull] MiniCPPParser.ConstDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.constructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorDecl([NotNull] MiniCPPParser.ConstructorDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.destructorDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDestructorDecl([NotNull] MiniCPPParser.DestructorDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] MiniCPPParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.controlStruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlStruct([NotNull] MiniCPPParser.ControlStructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] MiniCPPParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] MiniCPPParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MiniCPPParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] MiniCPPParser.ExprContext context);
}
